In [1]:
import pandas as pd
from IPython.display import display

In [4]:
df = pd.read_csv("../data/raw/pincode.csv")
df.head()

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
0,Telangana Circle,Hyderabad Region,Adilabad Division,Kothimir B.O,504273,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3638689,79.5376658
1,Telangana Circle,Hyderabad Region,Adilabad Division,Papanpet B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.4764899,79.5839230
2,Telangana Circle,Hyderabad Region,Adilabad Division,Kukuda B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,NaN,NaN
3,Telangana Circle,Hyderabad Region,Adilabad Division,Bareguda B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3285752,79.4760132
4,Telangana Circle,Hyderabad Region,Adilabad Division,Mosam B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3778044,79.6165209

In [5]:
df.shape

(165627, 11)

In [6]:
df.duplicated().sum()

np.int64(2)

In [22]:
# Remove duplicates
df = df.drop_duplicates().reset_index(drop=True)
df.shape

(21162, 3)

In [7]:
# check null values
df.isnull().sum()

circlename          0
regionname        315
divisionname        0
officename          0
pincode             0
officetype          0
delivery            0
district          715
statename         715
latitude        12007
longitude       12002
dtype: int64

In [ ]:
# checking duplicates with statename, district, pincode
df[df.duplicated(subset=["statename", "district", "pincode"])]

,circlename,regionname,divisionname,officename,pincode,officetype,delivery,district,statename,latitude,longitude
2,Telangana Circle,Hyderabad Region,Adilabad Division,Kukuda B.O,504299,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,NaN,NaN
4,Telangana Circle,Hyderabad Region,Adilabad Division,Mosam B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3778044,79.6165209
5,Telangana Circle,Hyderabad Region,Adilabad Division,Penchikalpet B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.2402360,79.8205696
7,Telangana Circle,Hyderabad Region,Adilabad Division,Old Town B.O,504296,BO,Non Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,19.3454350,79.4782916
8,Telangana Circle,Hyderabad Region,Adilabad Division,Kammergaon B.O,504296,BO,Delivery,KUMURAM BHEEM ASIFABAD,TELANGANA,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
165620,West Bengal Circle,South Bengal Region,Tamluk Division,Narghat SO,721633,PO,Delivery,MEDINIPUR EAST,WEST BENGAL,22.0758000,87.5322000
165621,West Bengal Circle,South Bengal Region,Tamluk Division,Panskura RS SO,721152,PO,Delivery,MEDINIPUR EAST,WEST BENGAL,22.3930278,87.7428056
165622,West Bengal Circle,South Bengal Region,Tamluk Division,Raghunathbari SO,721634,PO,Delivery,MEDINIPUR EAST,WEST BENGAL,22.3536629,87.7976060
165623,West Bengal Circle,South Bengal Region,Tamluk Division,Ramchandrapur SO East Midnapore,721647,PO,Delivery,MEDINIPUR EAST,WEST BENGAL,22.2975,87.7542
165624,West Bengal Circle,South Bengal Region,Tamluk Division,Srirampur Mid SO,721651,PO,Delivery,MEDINIPUR EAST,WEST BENGAL,22.3031210,87.9135540

In [19]:
# using only those columns and removing duplicates
df = (
    df[["statename", "district", "pincode"]]
    .drop_duplicates()
    .reset_index(drop=True)
    .copy()
)

In [20]:
df.shape

(21162, 3)

In [21]:
# check unique pincodes
df["pincode"].nunique()

19586

In [25]:
# cheking unique states
df["statename"].unique(), df["statename"].nunique()

(array(['TELANGANA', 'ANDHRA PRADESH', 'ASSAM', nan, 'BIHAR',
        'CHHATTISGARH', 'MEGHALAYA', 'JHARKHAND', 'KARNATAKA',
        'HIMACHAL PRADESH', 'JAMMU AND KASHMIR', 'LADAKH', 'GUJARAT',
        'THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'HARYANA', 'DELHI',
        'MAHARASHTRA', 'KERALA', 'MANIPUR', 'MIZORAM', 'NAGALAND',
        'PUDUCHERRY', 'MADHYA PRADESH', 'GOA', 'PUNJAB', 'RAJASTHAN',
        'ODISHA', 'TRIPURA', 'ARUNACHAL PRADESH', 'TAMIL NADU',
        'CHANDIGARH', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL',
        'ANDAMAN AND NICOBAR ISLANDS', 'SIKKIM', 'LAKSHADWEEP'],
       dtype=object),
 36)

In [26]:
# check null values
df.isnull().sum()

statename    338
district     338
pincode        0
dtype: int64

In [ ]:
# testing
import requests

In [15]:
df.duplicated(subset=["statename", "district", "pincode"])

0         False
1         False
2          True
3         False
4          True
          ...
165622     True
165623     True
165624     True
165625    False
165626    False
Length: 165627, dtype: bool

In [12]:
fil_df[fil_df.duplicated()]

          statename                district  pincode
2         TELANGANA  KUMURAM BHEEM ASIFABAD   504299
4         TELANGANA  KUMURAM BHEEM ASIFABAD   504296
5         TELANGANA  KUMURAM BHEEM ASIFABAD   504296
7         TELANGANA  KUMURAM BHEEM ASIFABAD   504296
8         TELANGANA  KUMURAM BHEEM ASIFABAD   504296
...             ...                     ...      ...
165620  WEST BENGAL          MEDINIPUR EAST   721633
165621  WEST BENGAL          MEDINIPUR EAST   721152
165622  WEST BENGAL          MEDINIPUR EAST   721634
165623  WEST BENGAL          MEDINIPUR EAST   721647
165624  WEST BENGAL          MEDINIPUR EAST   721651

[144465 rows x 3 columns]